export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE';
export const SET_VISIBLE_JOBS='SET_VISIBLE_JOBS';
export const SET_START_INDEX='SET_START_INDEX';