export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE';
export const SET_FILTER_SUCCESS="SET_FILTER_SUCCESS";
export const SET_FILTER_LOADING="SET_FILTER_LOADING";